### ISSUE TITLE
Values for simulating failed or successful transactions in sandbox not returning expected responses.

### ISSUE THREAD

**Issue by tim-626** [CyberSource/cybersource-rest-client-dotnet#102]
The following page lists a large set of "FDC Nashville Global Credit Card Error Testing Responses" values that are supposed to trigger various responses that can be used for testing in a sandbox:
https://developer.cybersource.com/hello-world/testing-guide.html

However, when I attempt to use them, they aren't returning the expected responses.  These "FDC Nashville" codes are listed in a section called "Processor Specifc [sic] Testing Triggers" so I'm thinking perhaps our account is using some other "Processor" but if this is the case I cannot find any information about where to look for alternative trigger values.

If anyone has any insights into what I might need to do to either get these "FDC Nashville" triggers working or use some other set of processor triggers or ???, I'd very much appreciate the help!  I'm happy to provide any information about our account or environment that might be of use.

**Comment by tim-626** [comment]
In case it helps, here's an example.  So far all the documented "TotalAmount" codes I've tried so far just don't match the expected results.  For instance, 3000.31, 3000.32, 3000.33 all come back as AUTHORIZED when they should be DECLINED.

For fun I tried using 2000.00 and this actually did come back DECLINED but I just arbitrarily tried it and it isn't documented.

Credit Card details such as the card number (4111111111111112) or invalid expiration dates do work as expected.  It's just these TotalAmount codes that aren't working.

```csharp
    class Program
    {
        static void Main(string[] args)
        {
            var configDict = new Dictionary<string, string>() {
                { "authenticationType", "HTTP_SIGNATURE" },
                { "merchantID", "..." },
                { "merchantsecretKey", "..." },
                { "merchantKeyId", "..." },
                { "runEnvironment", "cybersource.environment.sandbox" },
                { "useMetaKey", "false" }
            };
            var config = new Configuration(merchConfigDictObj: configDict);

            var request = new CreatePaymentRequest(
                ClientReferenceInformation: new Ptsv2paymentsClientReferenceInformation("ORDER000123"),
                ProcessingInformation: new Ptsv2paymentsProcessingInformation(Capture: true, CommerceIndicator: "internet"),
                PaymentInformation: new Ptsv2paymentsPaymentInformation(Card: new Ptsv2paymentsPaymentInformationCard(
                    Number: "4111111111111111",
                    ExpirationMonth: "12",
                    ExpirationYear: "2025",
                    Type: "001")),
                OrderInformation: new Ptsv2paymentsOrderInformation(
                    AmountDetails: new Ptsv2paymentsOrderInformationAmountDetails(
                        TotalAmount: "3000.31", // 3000.32, 3000.33, etc.
                        Currency: "USD"
                    ),
                    BillTo: new Ptsv2paymentsOrderInformationBillTo(
                        FirstName: "John",
                        LastName: "Doe",
                        Address1: "1234 Main Street",
                        Address2: "Suite 101",
                        Locality: "Smallville",
                        AdministrativeArea: "KS",
                        PostalCode: "12345",
                        Country: "USA",
                        Email: "test@test.com",
                        PhoneNumber: "123-456-7890"
                    )
                )
            );
            try
            {
                PaymentsApi paymentsInstance = new PaymentsApi(config);
                var response = paymentsInstance.CreatePayment(request);
                Console.WriteLine($"Status: {response.Status}");
            }
            catch (ApiException ex)
            {
                Console.WriteLine("Error");
                Console.WriteLine(ex.ErrorCode);
                Console.WriteLine(ex.ErrorContent);
            }

            Console.ReadLine();
            Console.WriteLine("End");
        }
    }
```

**Comment by londhegaurav** [comment]
@tim-626 You MID should be configured to right processor to tests the triggers, By default it is assigned to ChasePaymentech.
Please call support to get the processor configuration changed - 1.888.330.2300.

Also, We are about to upgrade testing trigger page on Prod. But below is the one on our sandbox environment that you can use in meantime. Let me know how it goes. Feel free to reach out on developer@cybersource.com for any other integration questions.

https://developer.cas.cybersource.com/hello-world/testing-guide.html?search=FDC-Nashville-Global

**Comment by tim-626** [comment]
@londhegaurav, thank you for the response!  This got me on the right path to get setup on the right processor.  Still not there due to some unrelated issues with our particular CyberSource account, but I'm confident we'll be able to get things sorted.
