### ISSUE TITLE
CSharp samples failing from duplicate header

### ISSUE THREAD

**Issue by fdgit** [CyberSource/cybersource-rest-client-dotnet#182]
The csharp samples fail with an exception.  For example, if one runs the RetrieveCustomer sample, it fails with:
- System.ArgumentException: 'An item with the same key has already been added. Key: Vary'
on the line
PostCustomerRequest result = apiInstance.GetCustomer(customerTokenId);

The headers being returned from test include 3 "Vary" headers, which cause an exception because the headers are placed in a dictionary.  (This just started happening - I first noticed it on 8/12/24.)
I believe duplicate response headers should be in comma delimited lists in the response, so it seems that the response headers have changed recently.

**Comment by ralreegorganon** [comment]
I've also encountered this in our usage of this API, around the same time.

**Comment by fdgit** [comment]
so not just me, thanks. 
I forked a fix for .net standard, probably same or similar will work for .net
I'd expect them to fix it on the service.  Testing the client libraries really should be part of changing the web service.
https://github.com/fdgit/cybersource-rest-client-dotnetstandard.

**Comment by wrightsonm** [comment]
We encountered this in the cybersource production environment about a month ago (the issue wasn't present in the test environment at the time...!).  I believe they reverted that change.  But just in case it reoccurs, we  also patched the header bug in our internal fork of the repo.

**Comment by gaubansa** [comment]
Thanks for reporting the issue for duplicate response key in SDK. We have fixed the issue in SDK from version v0.0.1.45 onwards.
