### ISSUE TITLE
Don't console.log in an SDK

### ISSUE THREAD

**Issue by jpknoll** [CyberSource/cybersource-rest-client-dotnet#19]
https://github.com/CyberSource/cybersource-rest-client-dotnet/blob/a4e61267ed98f4e91cb903294a22eea1126c2d98/Client/ApiClient.cs#L242

SDKs/Libraries shouldn't log to the console. Please use one of the many standard logging frameworks made available on the platform, like Microsoft.Extensions.ILogger.

**Comment by Digiman** [comment]
Agree with it. It would be better to migrate to Microsoft.Extension.Logging framework that provide base functionality for logging. In my pull request #22 i removed this partially and maybe after merging my changes with migration to .NET Standard 2.0 we can do it. 
Thanks.

**Comment by joesolano** [comment]
I second this request, seems odd for an SDK to Console.Writeline.

**Comment by xantari** [comment]
I also seen this. This API is not ready for prime time. I have found many bugs on it!
