### ISSUE TITLE
ApiClient.cs MerchantConfig Not Being Reset Properly

### ISSUE THREAD

**Issue by wasimhayatt1** [CyberSource/cybersource-rest-client-dotnet#21]
We are currently utilizing the CyberSource API to pull user info using the UserManagementApi. We need to pull our user listing for multiple merchants. So we plan on loading all of the merchants with their corresponding API keys and looping through and calling the UserManagementAPI.

This is how that looks:

**Retrieve Users from Merchants**
``` VB.NET
Dim Merchants As List(Of Merchant) = New List(Of Merchant)

Dim merch1 As New Merchant With {.MerchantID = "xxxxxxx", .SerialNumber = "xxxxxxx", .SecretKey = "xxxxxxx="}
Dim merch2 As New Merchant With {.MerchantID = "xxxxxxx", .SerialNumber = "xxxxxxx", .SecretKey = "xxxxxxx"}
Dim merch3 As New Merchant With {.MerchantID = "xxxxxxx", .SerialNumber = "xxxxxxx", .SecretKey = "xxxxxxx"}

Merchants.Add(merch1)
Merchants.Add(merch3)
Merchants.Add(merch2)

ServicePointManager.Expect100Continue = True
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12

For Each Merchant In Merchants
    Dim ConfigDictionary As Dictionary(Of String, String) = New Configuration().GetConfiguration(MerchantID:=Merchant.MerchantID,SecretKey:=Merchant.SecretKey, SerialNumber:=Merchant.SerialNumber)
    Dim ClientConfig As Client.Configuration = New CyberSource.Client.Configuration(merchConfigDictObj:=ConfigDictionary)
    Dim APIInstance As Api.UserManagementApi = New CyberSource.Api.UserManagementApi(ClientConfig)

    Dim ConfigDictionary As Dictionary(Of String, String) = New Configuration().GetConfiguration()
    Dim ClientConfig As Client.Configuration = New CyberSource.Client.Configuration(merchConfigDictObj:=ConfigDictionary)
    Dim APIInstance As Api.UserManagementApi = New CyberSource.Api.UserManagementApi(ClientConfig)
    Dim Result = As Model.UmsV1UsersGet200Response = APIInstance.GetUsers(organizationId:=Merchant .MerchantID)

''' Process results
Next
```

**Configuration class**
``` VB.NET
Public Class Configuration
    Private _configurationDictionary As New Dictionary(Of String, String)

    Public Function GetConfiguration(ByVal MerchantID As String, ByVal SecretKey As String, ByVal SerialNumber As String) As Dictionary(Of String, String)
        _configurationDictionary.Add("authenticationType", "HTTP_SIGNATURE")
        _configurationDictionary.Add("merchantID", MerchantID)
        _configurationDictionary.Add("merchantsecretKey", SecretKey)
        _configurationDictionary.Add("merchantKeyId", SerialNumber)
        ''_configurationDictionary.Add("keysDirectory", "Resource")
        _configurationDictionary.Add("runEnvironment", "cybersource.environment.production")

        Return _configurationDictionary

    End Function
End Class
```

This works great for the first merchant in the list but once we get to the second, we get an unauthorized 401 code even though we can validate that it works if we put it in the beginning of the list. 

What I believe is happening is when we call **UserManagementApi.cs** initially we will set this

``` C#
// ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
```

However, on the second call of the UserManagementApi when we are ready to process the next merchant **Configuration.ApiClient.Configuration** is already set therefore we don't reset it with the new configuration for the new merchant. 

That becomes an issue when we get to **ApiClient.cs** to get the merchant config and generate the authentication header as we start populating it with the previous merchant id which causes the 401 not authorized to return.

``` VB.NET
var merchantConfig = Configuration.MerchantConfigDictionaryObj != null
                ? new MerchantConfig(Configuration.MerchantConfigDictionaryObj)
                : new MerchantConfig();


........

//generate signature and set HTTP Signature headers
                var httpSign = authorize.GetSignature();
                authenticationHeaders.Add("v-c-merchant-id", httpSign.MerchantId);
```

Not sure if this is by design or an issue, but we were able to get around this by adding the following line of code to ensure that **Configuration.ApiClient.Configuration** gets reset.
``` VB.NET
ClientConfig.ApiClient.Configuration = Nothing '' Set to nothing to ensure we reset
```

``` VB.NET
Dim Merchants As List(Of Merchant) = New List(Of Merchant)

Dim merch1 As New Merchant With {.MerchantID = "xxxxxxx", .SerialNumber = "xxxxxxx", .SecretKey = "xxxxxxx="}
Dim merch2 As New Merchant With {.MerchantID = "xxxxxxx", .SerialNumber = "xxxxxxx", .SecretKey = "xxxxxxx"}
Dim merch3 As New Merchant With {.MerchantID = "xxxxxxx", .SerialNumber = "xxxxxxx", .SecretKey = "xxxxxxx"}

Merchants.Add(merch1)
Merchants.Add(merch3)
Merchants.Add(merch2)

ServicePointManager.Expect100Continue = True
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12

For Each Merchant In Merchants
    Dim ConfigDictionary As Dictionary(Of String, String) = New Configuration().GetConfiguration(MerchantID:=Merchant.MerchantID,SecretKey:=Merchant.SecretKey, SerialNumber:=Merchant.SerialNumber)
    Dim ClientConfig As Client.Configuration = New CyberSource.Client.Configuration(merchConfigDictObj:=ConfigDictionary)
    Dim APIInstance As Api.UserManagementApi = New CyberSource.Api.UserManagementApi(ClientConfig)

    Dim ConfigDictionary As Dictionary(Of String, String) = New Configuration().GetConfiguration()
    Dim ClientConfig As Client.Configuration = New CyberSource.Client.Configuration(merchConfigDictObj:=ConfigDictionary)
    ClientConfig.ApiClient.Configuration = Nothing '' Set to nothing to ensure we reset
    Dim APIInstance As Api.UserManagementApi = New CyberSource.Api.UserManagementApi(ClientConfig)
    Dim Result = As Model.UmsV1UsersGet200Response = APIInstance.GetUsers(organizationId:=Merchant .MerchantID)

''' Process results
Next
```

**Comment by xavicosta** [comment]
This issue is not just about the apiclient keeping the reference to the config but also the DefaultHeader being cached.

So this a workaround to reset the config values before calling the api to generate a key. 

```
            var clientConfig = new Configuration
            {
                MerchantConfigDictionaryObj = new ReadOnlyDictionary<string, string>(configDictionary),
                DefaultHeader = new Dictionary<string, string>(),
                ApiClient = {Configuration = null}
            };

            var apiInstance = new KeyGenerationApi(clientConfig);
            
            var result = apiInstance.GeneratePublicKey(requestObj);
```

**Comment by wasimhayatt1** [comment]
> This issue is not just about the apiclient keeping the reference to the config but also the DefaultHeader being cached.
> 
> So this a workaround to reset the config values before calling the api to generate a key.
> 
> ```
>             var clientConfig = new Configuration
>             {
>                 MerchantConfigDictionaryObj = new ReadOnlyDictionary<string, string>(configDictionary),
>                 DefaultHeader = new Dictionary<string, string>(),
>                 ApiClient = {Configuration = null}
>             };
> 
>             var apiInstance = new KeyGenerationApi(clientConfig);
>             
>             var result = apiInstance.GeneratePublicKey(requestObj);
> ```

I noticed that as well, hopefully this gets fixed and a workaround is not needed.

**Comment by gnongsie** [comment]
Hi,
Thank you for bringing this to our attention. We are looking into this and will update you when we make a fix.

**Comment by xantari** [comment]
We also have this problem. This is a critical failure. We can not make more than one call without "newing" everything all over again. This is because the "Signature" http header is not being re-generated when you call a different end point.

**Comment by snavinch** [comment]
This has been fixed in our latest release.

**Comment by xantari** [comment]
Which release is this fixed in? I don't see a corresponding code checkin that has this fixed, if there was it was not attached to this issue. Can you please attach the code checkin that supposedly fixes this? We are using latest release and don't see anything fixed.

**Comment by xantari** [comment]
I think I found the commit: https://github.com/CyberSource/cybersource-rest-client-dotnet/commit/992dac8ac238672c849cf1da0be14927f8fe9356

It was tagged with CYBSDX-78 instead of tagging this issue list as well which is why I didn't see it. I think i'll have to publish another bug due to the http header signature regeneration issue when calling multiple API's methods with the same ApiClient where it doesn't regenerate the Signature http header
