### ISSUE TITLE
Dependencies such as RestSharp are not present in the Nuget package

### ISSUE THREAD

**Issue by brianmc** [CyberSource/cybersource-rest-client-dotnet#24]
When I pull in the cybersource-rest-client nuget package for this SDK into a new project and attempt to use the Configuration class I get a class initializer error "The type initializer for 'CyberSource.Client.Configuration' threw an exception." File Not Found for RestSharp.  Seems like the RestClient timeout at line 112 is the issue.  https://github.com/CyberSource/cybersource-rest-client-dotnet/blob/master/Client/Configuration.cs#L112  

Does the Nuget package need to pull in it's dependent packages on install?

**Comment by gnongsie** [comment]
Hi,
For fixing these issues (missing dependencies), kindly refer to the [packages.config of the Sample project](https://github.com/CyberSource/cybersource-rest-samples-csharp/blob/master/src/packages.config). These dependencies must also be included in the project in order to properly use this SDK.

**Comment by Digiman** [comment]
I also had this issue but in my updated library this issue fixed and create proper Nuspec file. #22 - pull request with all this changes.

I am waiting almost a month to integrate this changes. :(((

@gnongsie or @akshunyaInfy please look at the pull request #22.

Thanks.

**Comment by alexcon92** [comment]
This should really be changed asap, it's a pointless headache for anyone wanting to use the SDK.

**Comment by gnongsie** [comment]
Hi,

Thank you for bringing this to our attention.

This issue has been addressed in the latest version of the SDK. 
Kindly fetch the SDK from NuGet **(v0.0.0.10)** and check again.

**Comment by snavinch** [comment]
Closing this as it has been addressed, kindly open a new one for any future issues
