### ISSUE TITLE
Json Serializer should not have indent formatting

### ISSUE THREAD

**Issue by brianmc** [CyberSource/cybersource-rest-client-dotnet#27]
For the Flex GenerateKey request the JSON needs to be used directly as a javascript object and should not contain any formatting. Line 108 in https://github.com/CyberSource/cybersource-rest-client-dotnet/blob/master/Model/FlexV1KeysPost200ResponseJwk.cs should not use the overload version with a formatter, the default is no formatting.

**Comment by gnongsie** [comment]
The default mustache file for this model contains the formatting. But I will have a command to remove the formatting settings in this case.
