### ISSUE TITLE
GetTransactionBatches Unauthorized

### ISSUE THREAD

**Issue by AndrewJamesMills** [CyberSource/cybersource-rest-client-dotnet#30]
The GetTransactionBatches call returns a 401.

Using the Developer portal, my credentials work correctly.  Executing within this client, a 401 is returned.  Even using the generated sample code from the portal below inside of the samples project the same result is returned.  The GetConfiguration() dictionary works successfully with other calls.  Just not this one.

```csharp
var startTime = DateTime.ParseExact("2019-04-11T22:47:57Z", "yyyy-MM-ddTHH:mm:ssZ", CultureInfo.InvariantCulture);
var endTime = DateTime.ParseExact("2019-05-01T22:47:57Z", "yyyy-MM-ddTHH:mm:ssZ", CultureInfo.InvariantCulture);

var configDictionary = new Configuration().GetConfiguration();
var clientConfig = new CyberSource.Client.Configuration(merchConfigDictObj: configDictionary);
var apiInstance = new TransactionBatchesApi(clientConfig);

var result = apiInstance.GetTransactionBatches(startTime, endTime);
Console.WriteLine(result);
```

**Comment by snavinch** [comment]
This doesn't seem to be an issue.
