### ISSUE TITLE
Structure incompatibility when deserilizing transaction details response.

### ISSUE THREAD

**Issue by KodiakMatt** [CyberSource/cybersource-rest-client-dotnet#32]
The response returned from a transaction detail request sent to "cybersource.environment.sandbox" has an "orderInformation.billTo" structure that contains a string property for "company" rather than JSON structure compatible with "Ptsv2paymentsOrderInformationBillToCompany". For our tests to complete successfully, we changed the Company property on "TssV2TransactionsGet200ResponseOrderInformationBillTo" to be a string for now. We're concerned about this mismatch. Are we encountering a server API version compatibility issue or should the REST client be updated to support both potential response formats? (Related to #25)

**Comment by gnongsie** [comment]
Hi,

Thank you for bringing this to our attention.

This issue has been addressed in the latest version of the SDK. 
Kindly fetch the SDK from NuGet **(v0.0.0.10)** and check again.

**Comment by KodiakMatt** [comment]
We're running with a customized version for now and will evaluate the nuget package again at our next upgrade point. This looks good based on a review of the changes made though. Thanks for the follow-up.
