### ISSUE TITLE
How to perform integration testing, or override hostname or baseurl

### ISSUE THREAD

**Issue by darrenliddell** [CyberSource/cybersource-rest-client-dotnet#35]
I'm trying to write an integration test for come client code that uses this SDK, for the test, I want the API request to hit an internal (in the test process) http endpoint. whilst one of the constructors for ApiClient hint this can be done, in practice when you make an api call (like PaymentApi CreatePayment) there is a call to CallAuthenticationHeaders and this creates a MerchantConfig (from the authentication sdk), which can only use one of 2 runEnvironments to derive a hostname, that CallAuthenticationHeaders  uses to construct a new RestClient:
e.g.:  RestClient = new RestClient("https://" + merchantConfig.HostName);   

I can't seam to override HostName, is there anyway to do this? (this is an integration test not unit, so I want a real http request)

**Comment by gnongsie** [comment]
Hi,
Thank you for coming to us with this issue.

I'm not sure what internal HTTP endpoint you are using. But we do have a Sandbox environment where you can test the integration with your application.

The SDK allows you to send requests to a production URL and a sandbox URL. We cannot allow you to send requests to a random URL.

CyberSource processes a lot of sensitive information, and these SDKs are designed to allow the merchants to protect themselves against fraud as well as to protect their customers against security threats.

For this reason, the SDKs exposed on external repositories (like NuGet) cannot allow you to send this sensitive data to a random URL. We are restricting those endpoints to the production URL and the sandbox URL.

The code in these GitHub repos is maintained to allow developers such as yourself to see the code behind those exposed SDKs. You are free to make code changes as you wish to your copy of the code. But again, for security reasons, we cannot make similar changes to the code to allow sending requests to random URLs.

I hope you can understand. Kindly let me know how else I can assist you.

Thanks,
Gabriel

**Comment by darrenliddell** [comment]
Ok, thanks for the feed back, and I understand your perspective, just to clarify:

I agree that having access to a sandbox test for manual testing is great, the tester can submit a payment, and they check on Cybersource portal to see the response. In this case I'm looking at an automated test, that's ran everytime the client code is changed, to make sure when the client application is asked to send a payment to cybersource it does so, and this done consistently by the code. So for this the test receives the response.

Now the SDK is great for automated unit testing, as you've provided some good interfaces.

I'm reluctant to fork the code, to allow me to override, as that will just generate more downstream activity, I can take steps so the build server DNS lookup of apitest.cybersource.com will just return the loopback ip address.

Also its a bit misleading that the SDK allows, and documents, creating the ApiClient with a new baseUrl:

`/// <summary>

        /// Initializes a new instance of the <see cref="ApiClient" /> class

        /// with default configuration.

        /// </summary>

        /// <param name="basePath">The base path.</param>

        public ApiClient(String basePath = "https://apitest.cybersource.com")

        {

           if (String.IsNullOrEmpty(basePath))

                throw new ArgumentException("basePath cannot be empty");



            RestClient = new RestClient(basePath);

            Configuration = Configuration.Default;

        }`

I'll keep checking in case you change your minds in the future ;-)

Darren
