### ISSUE TITLE
Critical Bug in DownloadReportAsyncWithHttpInfo

### ISSUE THREAD

**Issue by xantari** [CyberSource/cybersource-rest-client-dotnet#36]
In the DownloadReportAsyncWithHttpInfo class when requesting a report you do not get any report data back!

I decompiled your library and found the issue.

I have highlighted issue in RED:

![image](https://user-images.githubusercontent.com/6610039/60305752-469a9c00-9903-11e9-99a0-18ad196bfeff.png)

If you look at the non async version you get this:

![image](https://user-images.githubusercontent.com/6610039/60305777-5b772f80-9903-11e9-80b7-63baa827e8d7.png)

You are missing restResponse.get_Content()!!!!

You are requesting everyone to convert to new REST Report download by 7/31/2019, but have such critical bug to disallow async function???

**Comment by Digiman** [comment]
As I remember i also found this problem and fix it in my form to make sure that i can use API and download report - this is main functionality for now that required to work. I am continue using my solution that works.
This repository and library contains a lot of issues (because for now I need only reports I have fixed it for me, other APIs - may also contains issues) that need to be resolved. But as I an see authors who work with it don't want to do this. It's horrible...(((

@xantari try to take a look on my fork - at least downloading reports is working. 

Thanks.

**Comment by xantari** [comment]
@Digiman Thanks! I've started fixing the pieces so far that I have found for just the reporting infrastructure. It's unbelievable to me that only one Cybersource developer is assigned to this (and only part time as indicated by his checkin requests accross Python, Ruby, PHP, and C# librarys).

It's amazing to me that Cybersource is telling people to switch to the new REST API by 7/31/2019, but don't provide the proper client library abstractions to do so. Talk about the cart before the horse! Upper management at Cybersource should be rethinking their 7/31/2019 deadline in light of these issues. But alas, it is probably falling on deaf ears.

**Comment by Digiman** [comment]
@xantari Yep, I think so. It's really bad approach. I had discussion with guy from CyberSource (some kind manager) that talking and talking without stop. I said that library need to be improved but ... nothings changed.

It's part of he problem. Also they had issues inside report. It's more fully - it like as they don't have any testing (QA).

At least for now - my solution working. Hope it will work in future. Maybe in 1-2 years they will provide proper logic and working library)

**Comment by xantari** [comment]
Cybersource support case # 06135500 stated this works fine for them. They said "For issue 36, our engineers were able to receive the report information back in the console." 

Here is the failing lines of code:

https://github.com/CyberSource/cybersource-rest-client-dotnet/blob/d235961f9ce586fbfdf75a58b1efe8cb5fa0a690/Api/ReportDownloadsApi.cs#L335-L337

Here is the non-async working version lines of code:

https://github.com/CyberSource/cybersource-rest-client-dotnet/blob/d235961f9ce586fbfdf75a58b1efe8cb5fa0a690/Api/ReportDownloadsApi.cs#L258-L260

You will notice that in the working non-async version above you have this: localVarResponse.Content

But it is missing in the Async version. This is where your bug is. You are not returning the content of the report in the Async version.

**Comment by gnongsie** [comment]
Hi,

Thank you for bringing this to our attention.

This issue has been addressed in the latest version of the SDK. 
Kindly fetch the SDK from NuGet (v0.0.0.10) and check again.

**Comment by xantari** [comment]
Appears to be fixed
