### ISSUE TITLE
Why two different reports API's?

### ISSUE THREAD

**Issue by xantari** [CyberSource/cybersource-rest-client-dotnet#39]
You have ReportsApi and ReportsDownloadsApi.

Why two? Why not everything under ReportsApi?

**Comment by gnongsie** [comment]
Hi,

The different APIs correspond to two different REST endpoints.

ReportsApi will send requests to https://apitest.cybersource.com/reporting/v3/reports (Sandbox) and https://api.cybersource.com/reporting/v3/reports (Production).

ReportDownloadsApi will send requests to https://apitest.cybersource.com/reporting/v3/report-downloads (Sandbox) and https://api.cybersource.com/reporting/v3/report-downloads (Production).

Similarly,

ReportDefinitionsApi will send requests to https://apitest.cybersource.com/reporting/v3/report-definitions/{reportDefinitionName} (Sandbox) and https://api.cybersource.com/reporting/v3/report-definitions/{reportDefinitionName} (Production).

ReportSubscriptionsApi will send requests to https://apitest.cybersource.com/reporting/v3/report-subscriptions/{reportName} (Sandbox) and https://api.cybersource.com/reporting/v3/report-subscriptions/{reportName} (Production).

**Comment by xantari** [comment]
Thanks. Closing.
