### ISSUE TITLE
HTTP Proxy configuration doesn't work

### ISSUE THREAD

**Issue by xantari** [CyberSource/cybersource-rest-client-dotnet#41]
The sample here shows that you can add proxyAddress and proxyPort and it will route the request through the proxy.

This does not function. HTTP Requests never arrive at proxy:

https://github.com/CyberSource/cybersource-rest-samples-csharp/blob/master/src/Configuration.cs

How to use proxy server?

**Comment by xantari** [comment]
Cybersource is now tracking this issue as cybsdx-105.

**Comment by Wind010** [comment]
I have a similar issue and requirement to support additional proxy configuration such as bypassOnLocal and byPassList.  I've forked and made changes to support System.Net.WebProxy through the CyberSource.Client.Configuration directly.  I will be testing through our environment.

https://github.com/Wind010/cybersource-rest-client-dotnet/pull/1

**Comment by snavinch** [comment]
Closing this issue as this has been fixed in v0.0.1.1
