### ISSUE TITLE
ApiClient.Deserialize has magic strings and should be removed

### ISSUE THREAD

**Issue by xantari** [CyberSource/cybersource-rest-client-dotnet#46]
There is code like this:

if (type.Name.StartsWith("System.Nullable`1[[System.DateTime"))

Which is not good way to do it as it is magic string and bloats framework code.

It should be this:

if ( type == typeof(DateTime?)) 

What about regular DateTime (non nullable)?

**Comment by gnongsie** [comment]
Hi,

Thank you for bringing this to our attention.

This issue has been addressed in the latest version of the SDK. 
Kindly fetch the SDK from NuGet (**v0.0.0.10**) and check again.

For DateTime (non-nullable), I have replied to it in #43. Kindly refer to my comments there.
