### ISSUE TITLE
Invalid parameter "OrganizationId"

### ISSUE THREAD

**Issue by superallumette** [CyberSource/cybersource-rest-client-dotnet#50]
Hello,

Since the last update, we have errors while calling ConversionReport with the following error :
"Invalid parameter organizationId".
After some investigations, we have figured out this was caused by the organizationId parameter being added to the request URL.
This parameter is optional and therefore should not be present if empty. The same request without the parameter succeeds just fine.

**Comment by xantari** [comment]
This is similar to #43 Their method signatures are not correct. We noticed this organizationId issue with the SearchReportsWithHttpInfo as well, which indicates the parameter is not required, but yet it is.

**Comment by gnongsie** [comment]
Hi,

Thank you for bringing this to our attention.

This issue has been addressed in the latest version of the SDK. 
Kindly fetch the SDK from NuGet (**v0.0.0.10**) and check again.
