### ISSUE TITLE
KeyGenerationApi / GeneratePublicKey Request is missing model data

### ISSUE THREAD

**Issue by xantari** [CyberSource/cybersource-rest-client-dotnet#60]
The KeyGenerationApi uses a model called GeneratePublicKeyRequest. The GeneratePublicKeyRequest  is missing the "targetOrigin" field.

As you can see this field is required for proper flex form creation and is available in the API indicated here:

http://apps.cybersource.com/library/documentation/dev_guides/hosted_flex/0_1_0/html/custom-server-integration/

However there is a documentation bug where it doesn't list it as a valid field in the Flex area here:

https://developer.cybersource.com/api/reference/api-reference.html

targetOrigin is infact a valid field.

There are two issues that need to be addressed here:

1. Your API documentation located here is incorrect:
https://developer.cybersource.com/api/reference/api-reference.html

2. Your .NET REST client is not correct as a result, the GeneratePublicKeyRequest request object needs that field added or you can not use the generated keys within the Flex Microform.

Here is the API that needs to be updated with the new field:

https://github.com/CyberSource/cybersource-rest-client-dotnet/blob/d235961f9ce586fbfdf75a58b1efe8cb5fa0a690/Api/KeyGenerationApi.cs

**Comment by ssethumavisa** [comment]
This is being fixed and tested, we will update once we release it.

**Comment by rochi1** [comment]
I have a workaround to this. 
I have inherited the GeneratePublicKeyRequest class and added the additional property. 
Swap out for this class and once it is serialized to JSON the api works.
```

using System.Text;
using Newtonsoft.Json;
using System.Runtime.Serialization;
using CyberSource.Model;


namespace TestApp.CybersourcePaymentGateway
{

        [DataContract]
        public class GeneratePublicKeyRequestFlex : GeneratePublicKeyRequest
        {
            [JsonConstructor]
            protected GeneratePublicKeyRequestFlex()
            {
            }

            public GeneratePublicKeyRequestFlex(string encryptionType, string targetOrigin = null):base(encryptionType)
            {
                this.TargetOrigin = targetOrigin;
            }

        [DataMember(EmitDefaultValue = false, Name = "targetOrigin")]
        public string TargetOrigin { get; }

        public override string ToString()
            {
                StringBuilder stringBuilder = new StringBuilder();
                stringBuilder.Append("class GeneratePublicKeyRequest {\n");
                stringBuilder.Append("  EncryptionType: ").Append(this.EncryptionType).Append("\n");
                stringBuilder.Append("  TargetOrigin: ").Append(this.TargetOrigin).Append("\n");
            stringBuilder.Append("}\n");
                return stringBuilder.ToString();
            }




            public bool Equals(GeneratePublicKeyRequestFlex other)
            {
                if(!base.Equals(other))
                    return false;
                if (this.TargetOrigin == other.TargetOrigin)
                    return true;
                if (this.TargetOrigin != null)
                    return this.TargetOrigin.Equals(other.TargetOrigin);
                return false;
            }

            public override int GetHashCode()
            {
                int num = base.GetHashCode();
                if (this.TargetOrigin != null)
                    num = num * 59 + this.TargetOrigin.GetHashCode();
                return num;
            }

          
        }
    }


```

**Comment by snavinch** [comment]
This issue has been fixed in our latest release from the SDK and documentation perspective. Please validate. I'm closing the issue now. Feel free to contact us for any further issues
