### ISSUE TITLE
Enum types for ReportFrequency, ReportMimeType, Status disappeared in July 2019 update

### ISSUE THREAD

**Issue by xantari** [CyberSource/cybersource-rest-client-dotnet#61]
ReportingV3ReportsGet200ResponseReports use to have ReportFrequencyEnum, ReportMimeTypeEnum, and StatusEnum.

Now they are missing since July 2019 release.

See here where they were removed:

https://github.com/CyberSource/cybersource-rest-client-dotnet/commit/18ca933465e8cbe046b409af480de38b30ba1b6e#diff-3b2efc4a7d721f6bd55f4ec6caf99dd9

Please put back.

Additionally, the ReportingV3ReportsGet200ResponseReportSearchResults is also missing these enums.

**Comment by gnongsie** [comment]
Hi @xantari ,

CyberSource has decided not to support enums in the client SDK any further. This decision was made after a detailed analysis of the functionality provided by including enums, including (but not limited to) the enum value validation and missing enum values.

Further information about the valid values for these fields can be found here : https://developer.cybersource.com/api/reference/api-reference.html

You can use the left menu to navigate to `Reporting --> Retrieve available reports` and look in the `Request Field Description` for the fields that you are looking for.

Furthermore, the model `ReportingV3ReportsGet200ResponseReports` has been replaced by the model `ReportingV3ReportsGet200ResponseReportSearchResults` to match the behavior of the API.
