### ISSUE TITLE
SearchReportsAsyncWithHttpInfo broken but SearchReportsWithHttpInfo works

### ISSUE THREAD

**Issue by xantari** [CyberSource/cybersource-rest-client-dotnet#62]
When using SearchReportsAsyncWithHttpInfo you get an authentication error in .11, but SearchReportsWithHttpInfo works fine with the exact same parameters.

**Comment by xantari** [comment]
Any ETA on fix?

**Comment by xantari** [comment]
Anyone home??

**Comment by snavinch** [comment]
Closing this as it has been fixed in the latest version.
