### ISSUE TITLE
Add Flex Key verification routine to this library

### ISSUE THREAD

**Issue by xantari** [CyberSource/cybersource-rest-client-dotnet#64]
Currently this library provides a way to get Flex Keys (albeit incorrectly since it is missing the targetOrigin model property as indicated in #60).

What would be great is if it also had the Verify function that is found in the FlexServerSDK (which has a major bug that crashes IIS App Pools due to the crazy AppDomain code it interacts with that to this date has not been fixed).

That way we have a raw http library that can retrieve and verify flex tokens and there would be no need for that FlexServerSDK nuget project (which doesn't have a github btw to report bugs!!!)

**Comment by gnongsie** [comment]
Hi @xantari ,

Are you looking for something similar to this?

https://github.com/CyberSource/cybersource-rest-samples-csharp/blob/master/src/Samples/Flex/CoreServices/TokenizeCard.cs#L75-L97

**Comment by xantari** [comment]
@gnongsie Yep!

**Comment by xantari** [comment]
@gnongsie It looks like this was done in here: https://github.com/CyberSource/cybersource-rest-client-dotnet/blob/master/Utilities/Flex/TokenVerification/TokenVerificationUtility.cs

It would be helpful if you provide updates on this project by updating these issue submissions to notify people that they are done and tag this issue during your checkin.
