### ISSUE TITLE
Documentation for CyberSource.Model.CreateSearchRequest particularly the Query property.

### ISSUE THREAD

**Issue by multco-malan** [CyberSource/cybersource-rest-client-dotnet#79]
**May I please get some more documentation on how to use the Query property of CyberSource.Model.CreateSearchRequest?**

Both
https://github.com/CyberSource/cybersource-rest-client-dotnet/blob/master/docs/CreateSearchRequest.md
and
https://github.com/CyberSource/cybersource-rest-client-dotnet/blob/master/Api/SearchTransactionsApi.cs
are lacking when it comes to the mechanics of supplying ranges as
shown in the sample here:
https://github.com/CyberSource/cybersource-rest-samples-csharp/blob/master/src/Samples/TransactionSearch/CoreServices/CreateSearchRequest.cs

where 
Query = "clientReferenceInformation.code:TC50171_3 AND submitTimeUtc:[NOW/DAY-7DAYS TO NOW/DAY+1DAY}",

I can discern that CreateSearch() returns 
a TssV2TransactionsPost201Response which contains  a collection of 
TssV2TransactionsPost201ResponseEmbeddedTransactionSummaries
and that the search query property acts on nested properties such as ClientReferenceInformation.code with a dot notation and uses camel casing.

**What is not clear in this sample is the "submitTimeUtc:[NOW/DAY-7DAYS TO NOW/DAY+1DAY}"**
How am I supposed to know this syntax?
What does the "[" signify?
What does the "}" signify?
What type of language is this?

Where may I find the documentation please?

**Comment by snavinch** [comment]
Hi, Thanks for writing to us. The syntax is in alignment with the Apache Solr Date query. You can read about it [here](https://lucene.apache.org/solr/guide/6_6/working-with-dates.html). Please feel free to reach out to us in case of any other query.
