### ISSUE TITLE
Using rest client in SSIS package. Can not install cybersource-rest-client-dotnet.dll in GAC as it does not have a strong name.

### ISSUE THREAD

**Issue by multco-malan** [CyberSource/cybersource-rest-client-dotnet#80]
Hi,
I am trying to incorporate the cybersource-rest-client-dotnet in a SSIS dtsx package.
In order for this to run I understand that I need to install this in the Global Assembly Cache.
I am unable to do so because the assembly does not have a strong name.

**Comment by xantari** [comment]
Multco-malan,

You do not need to sign an SSIS package for it to run. You can make a direct reference to the DLL in your script task in SSIS and it will run just fine without it being signed.

We put ours in a directory such as C:\SSIS_DLLs to accomplish this.

**Comment by multco-malan** [comment]
thanks
